In [8]:
import pandas as pd

### ThEconSum

#### Abstractive

In [9]:
df_gemma_ab = pd.read_csv(
    r'F:\AI\Super AI SS4\Level 3 - INTERN\Jupyter Notebook\Evaluate\Long-News-ThEconSum\Abstractive\gemma2-ThEconSum-Evaluate-AB.csv')
df_llama_ab = pd.read_csv(
    r'F:\AI\Super AI SS4\Level 3 - INTERN\Jupyter Notebook\Evaluate\Long-News-ThEconSum\Abstractive\llama3-ThEconSum-Evaluate-AB.csv')
df_qwen_ab = pd.read_csv(
    r'F:\AI\Super AI SS4\Level 3 - INTERN\Jupyter Notebook\Evaluate\Long-News-ThEconSum\Abstractive\qwen2-ThEconSum-Evaluate-AB.csv')

In [10]:
print(f'Gemma2: {df_gemma_ab.shape}\nLlama3: {df_llama_ab.shape}\nQwen2: {df_qwen_ab.shape}')

Gemma2: (50, 9)
Llama3: (50, 9)
Qwen2: (49, 9)

##### Gemma2

In [11]:
df_gemma_ab.head(6)

,hypothesis,reference,BERT_Precision,BERT_Recall,BERT_F1,ROUGE-1,ROUGE-2,ROUGE-L,ROUGE_Score
0,\tงานวิจัยถือเป็นขั้นตอนสำคัญที่จะบอกว่าธุรกิจ...,\t10 บิ๊กบราเธอร์ (Big Brother) ที่พัฒนา รูปแบ...,0.825808,0.805484,0.815519,0.533030,0.266867,0.482916,0.427604
1,\tเมื่อวานนี้ MSCI ปรับลดน้ำหนักตลาดหุ้นไทย 1....,\tวานนี้ MSCI ปรับลดน้ำหนักตลาดหุ้นไทย 1.05 หม...,0.781536,0.785328,0.783427,0.633147,0.394702,0.607076,0.544975
2,\tข้อมูลจาก UNs World Population Prospects 201...,\tข้อมูลของ UNs World Population Prospects 201...,0.839029,0.851351,0.845145,0.647826,0.464238,0.621739,0.577934
3,\tนายพนม ควรสถาพร ประธานกรรมการบริหาร บริษัท เ...,\tAGE ยอดขายถ่านหินไตรมาสแรกพุ่งขึ้นเกือบเท่าต...,0.821049,0.805083,0.812988,0.626959,0.330579,0.570533,0.509357
4,\tบริษัท พีทีที โกลบอล เคมิคอล จำกัด (มหาชน) ห...,\tนายทิติพงษ์ จุลพรศิริดี ผู้จัดการฝ่ายหน่วยงา...,0.857326,0.856087,0.856706,0.732095,0.604575,0.673740,0.670137
5,\tในยุคโควิดที่เศรษฐกิจโลกชะลอตัว ธุรกิจกลุ่มเ...,คงกระพัน อินทรแจ้ง ประธานเจ้าหน้าที่ บริหาร บร...,0.786303,0.789773,0.788034,0.654054,0.405157,0.583784,0.547665

In [12]:
avg_gemma_ab = df_gemma_ab.select_dtypes(include='number').mean()
avg_gemma_ab

BERT_Precision    0.818673
BERT_Recall       0.816428
BERT_F1           0.817487
ROUGE-1           0.635784
ROUGE-2           0.400735
ROUGE-L           0.580107
ROUGE_Score       0.538875
dtype: float64

##### Llama3

In [13]:
df_llama_ab.head(6)

,hypothesis,reference,BERT_Precision,BERT_Recall,BERT_F1,ROUGE-1,ROUGE-2,ROUGE-L,ROUGE_Score
0,10 บิ๊กบราเธอร์ ที่พัฒนา รูปแบบธุรกิ...,\t10 บิ๊กบราเธอร์ (Big Brother) ที่พัฒนา รูปแบ...,0.924537,0.923285,0.923911,0.596330,0.409160,0.541284,0.515592
1,เมื่อวานนี้ MSCI ได้ปรับลดล้ำหนักตลา...,\tวานนี้ MSCI ปรับลดน้ำหนักตลาดหุ้นไทย 1.05 หม...,0.783934,0.787903,0.785914,0.650000,0.424886,0.625000,0.566629
2,จากข้อมูลของ UNs World Population Pr...,\tข้อมูลของ UNs World Population Prospects 201...,0.790502,0.791322,0.790911,0.661616,0.449045,0.636364,0.582341
3,ทันหุ้น-AGE ยอดขายถ่านหินไตรมาสแรกพุ...,\tAGE ยอดขายถ่านหินไตรมาสแรกพุ่งขึ้นเกือบเท่าต...,0.777822,0.749212,0.763249,0.504348,0.272566,0.423188,0.400034
4,ทันหุ้น - PTTGC ลุ้นรับรู้กำไรทันที ...,\tนายทิติพงษ์ จุลพรศิริดี ผู้จัดการฝ่ายหน่วยงา...,0.779957,0.788612,0.784261,0.714681,0.531732,0.664820,0.637078
5,ณัฐณิชา ดอนสุวรรณ กรุงเทพธุรกิจ ธุรก...,คงกระพัน อินทรแจ้ง ประธานเจ้าหน้าที่ บริหาร บร...,0.772256,0.780843,0.776526,0.680000,0.528548,0.630000,0.612849

In [14]:
avg_llama_ab = df_llama_ab.select_dtypes(include='number').mean()
avg_llama_ab

BERT_Precision    0.797874
BERT_Recall       0.796602
BERT_F1           0.797157
ROUGE-1           0.622739
ROUGE-2           0.415446
ROUGE-L           0.573546
ROUGE_Score       0.537244
dtype: float64

##### Qwen2

In [15]:
df_qwen_ab.head(6)

,hypothesis,reference,BERT_Precision,BERT_Recall,BERT_F1,ROUGE-1,ROUGE-2,ROUGE-L,ROUGE_Score
0,เริ่มต้นด้วยการพัฒนาธุรกิจเพื่อสังคมที...,\t10 บิ๊กบราเธอร์ (Big Brother) ที่พัฒนา รูปแบ...,0.725177,0.716700,0.720913,0.345048,0.119205,0.249201,0.237818
1,ทั้งหมดเป็นความรู้สึกต่อการเขียนหุ้นที่ไม่ได้ม...,\tวานนี้ MSCI ปรับลดน้ำหนักตลาดหุ้นไทย 1.05 หม...,0.726704,0.726263,0.726483,0.403183,0.162476,0.381963,0.315874
2,ทั่วโลก มีคนจำนวน 36 ล้านคนที่ต้องเผชิญกับปัญห...,\tข้อมูลของ UNs World Population Prospects 201...,0.720746,0.726226,0.723476,0.381818,0.118812,0.303030,0.267887
3,"ที่ผ่านมา, บริษัทได้ลงทุนสู่ผลิตภัณฑ์ที่มีมูลค...",\tนายทิติพงษ์ จุลพรศิริดี ผู้จัดการฝ่ายหน่วยงา...,0.776243,0.771263,0.773745,0.543046,0.286316,0.417219,0.415527
4,ที่วันที่ 22 มกราคม พ.ศ. 2564 PTTGC เข้าสู่กระ...,คงกระพัน อินทรแจ้ง ประธานเจ้าหน้าที่ บริหาร บร...,0.743761,0.751685,0.747702,0.578005,0.290657,0.501279,0.456647
5,ที่ผ่านมา ชานนท์จิตตชโลธร ผู้บริหารสถานีบริการ...,กระทรวงเกษตรและสหกรณ์ ร่วมกับ บริษัท ปตท. จำกั...,0.763173,0.753948,0.758533,0.513120,0.261719,0.396501,0.390447

In [16]:
avg_qwen_ab = df_qwen_ab.select_dtypes(include='number').mean()
avg_qwen_ab

BERT_Precision    0.755832
BERT_Recall       0.754997
BERT_F1           0.755359
ROUGE-1           0.487592
ROUGE-2           0.220487
ROUGE-L           0.415945
ROUGE_Score       0.374675
dtype: float64

#### Extractive

In [17]:
df_gemma_ex = pd.read_csv(
    r'F:\AI\Super AI SS4\Level 3 - INTERN\Jupyter Notebook\Evaluate\Long-News-ThEconSum\Extractive\gemma2-ThEconSum-Evaluate-EX.csv')
df_llama_ex = pd.read_csv(
    r'F:\AI\Super AI SS4\Level 3 - INTERN\Jupyter Notebook\Evaluate\Long-News-ThEconSum\Extractive\llama3-ThEconSum-Evaluate-EX.csv')
df_qwen_ex = pd.read_csv(
    r'F:\AI\Super AI SS4\Level 3 - INTERN\Jupyter Notebook\Evaluate\Long-News-ThEconSum\Extractive\qwen2-ThEconSum-Evaluate-EX.csv')

In [18]:
print(f'Gemma2: {df_gemma_ex.shape}\nLlama3: {df_llama_ex.shape}\nQwen2: {df_qwen_ex.shape}')

Gemma2: (50, 9)
Llama3: (50, 9)
Qwen2: (49, 9)

##### Gemma2

In [19]:
df_gemma_ex.head(6)

,hypothesis,reference,BERT_Precision,BERT_Recall,BERT_F1,ROUGE-1,ROUGE-2,ROUGE-L,ROUGE_Score
0,\tนายอนุสรณ์ แสงนิ่มนวล อดีตกรรมการผู้จัดการให...,นายอนุสรณ์ แสงนิ่มนวล กล่าวว่า การตั้งบรรษัทพล...,0.807995,0.820951,0.814421,0.677966,0.497427,0.672316,0.615903
1,\tทันทีที่เรียนจบปริญญาตรีวิศวกรรมเคมี ที่มหาว...,\tทันทีที่เรียนจบปริญญาตรีวิศวกรรมเคมี ที่มห...,0.934671,0.938156,0.936410,0.780142,0.560117,0.732861,0.691040
2,บริษัท พีทีที โกลบอล เคมิคอล จำกัด (มหาชน) หรื...,\t บริษัท พีทีที โกลบอล เคมิคอล จำกัด หรือ GC ...,0.869404,0.872554,0.870976,0.695402,0.522593,0.666667,0.628221
3,\tนายจักรพงส์ สุเมธโชติเมธา ประธาน เจ้าหน้าที่...,นายจักรพงส์ สุเมธโชติเมธา ประธานเจ้าห...,0.826899,0.835867,0.831359,0.721393,0.492091,0.686567,0.633351
4,\tนายชาญศิลป์ ตรีนุชกร ประธานเจ้าหน้าที่บริหาร...,นายชาญศิลป์ ตรีนุชกร ประธานเจ้าหน้าที่บริหารแล...,0.863537,0.827563,0.845168,0.766917,0.592949,0.746867,0.702244
5,\tขาโจ๋ปากซอย เริ่มต้นกับ SME D Bank จัดหนักเส...,SME D Bank สินเชื่อถูกสุดในระบบ 0.08%...,0.793792,0.798919,0.796347,0.554585,0.412860,0.532751,0.500065

In [20]:
avg_gemma_ex = df_gemma_ex.select_dtypes(include='number').mean()
avg_gemma_ex

BERT_Precision    0.841365
BERT_Recall       0.839486
BERT_F1           0.840367
ROUGE-1           0.693513
ROUGE-2           0.513326
ROUGE-L           0.676770
ROUGE_Score       0.627870
dtype: float64

##### Llama3

In [21]:
df_llama_ex.head(6)

,hypothesis,reference,BERT_Precision,BERT_Recall,BERT_F1,ROUGE-1,ROUGE-2,ROUGE-L,ROUGE_Score
0,นายอนุสรณ์ แสงนิ่มนวล อดีตกรรมการผู้...,นายอนุสรณ์ แสงนิ่มนวล กล่าวว่า การตั้งบรรษัทพล...,0.814033,0.824301,0.819135,0.705128,0.507099,0.653846,0.622025
1,ทันทีที่เรียนจบปริญญาตรีวิศวกรรมเคมี...,\tทันทีที่เรียนจบปริญญาตรีวิศวกรรมเคมี ที่มห...,0.833215,0.626514,0.715230,0.066351,0.036585,0.066351,0.056429
2,บริษัท พีทีที โกลบอล เคมิคอล จำกัด (...,\t บริษัท พีทีที โกลบอล เคมิคอล จำกัด หรือ GC ...,0.870065,0.873062,0.871561,0.717087,0.491429,0.666667,0.625061
3,ทันหุ้น - SKE ซุ่มดีลร่วมทุนโรงไฟฟ้า...,นายจักรพงส์ สุเมธโชติเมธา ประธานเจ้าห...,0.745019,0.688124,0.715442,0.220339,0.117647,0.203390,0.180459
4,ปั้นพื้นที่กว่า 3 พันไร่อีอีซีไอ รับ...,นายชาญศิลป์ ตรีนุชกร ประธานเจ้าหน้าที่บริหารแล...,0.822310,0.802868,0.812473,0.661202,0.463504,0.633880,0.586195
5,เริ่มต้นกับ SME D Bank จัดหนักเสิร์ฟ...,SME D Bank สินเชื่อถูกสุดในระบบ 0.08%...,0.819348,0.823957,0.821646,0.707547,0.544444,0.707547,0.653180

In [22]:
avg_llama_ex = df_llama_ex.select_dtypes(include='number').mean()
avg_llama_ex

BERT_Precision    0.819609
BERT_Recall       0.813765
BERT_F1           0.816330
ROUGE-1           0.637908
ROUGE-2           0.454370
ROUGE-L           0.612012
ROUGE_Score       0.568097
dtype: float64

##### Qwen2

In [23]:
df_qwen_ex.head(6)

,hypothesis,reference,BERT_Precision,BERT_Recall,BERT_F1,ROUGE-1,ROUGE-2,ROUGE-L,ROUGE_Score
0,นายนุสรณ์แสงนิ่มนวล อดีตกรรมการผู้จัดก...,นายอนุสรณ์ แสงนิ่มนวล กล่าวว่า การตั้งบรรษัทพล...,0.740492,0.714320,0.727171,0.643836,0.370536,0.547945,0.520772
1,บริษัท พีทีที โกลบอล เคมิคอล และบริษัท...,\t บริษัท พีทีที โกลบอล เคมิคอล จำกัด หรือ GC ...,0.800636,0.783434,0.791942,0.509934,0.253763,0.463576,0.409091
2,ทันหุ้น - SKE ซุ่มดีลร่วมกับผู้ซื้อที่ดินในจัง...,นายจักรพงส์ สุเมธโชติเมธา ประธานเจ้าห...,0.756907,0.739404,0.748053,0.491124,0.194617,0.443787,0.376509
3,ปั้นพื้นที่กว่า 3 พันไร่อีอีซีไอ รับนักลงทุนไท...,นายชาญศิลป์ ตรีนุชกร ประธานเจ้าหน้าที่บริหารแล...,0.765291,0.750095,0.757617,0.583851,0.312115,0.527950,0.474639
4,ส่วนของนายถวนันท์ ธเนศเดชสุนทร ผู้บริหารดี เวล...,SME D Bank สินเชื่อถูกสุดในระบบ 0.08%...,0.703047,0.707669,0.705351,0.437126,0.236111,0.401198,0.358145
5,สแกน อินเตอร์ หรือ SCN และปตท. ลงนามในสัญญาซื้...,ดร.ฤทธี กิจพิพิธ กรรมการผู้จัดการใหญ...,0.785405,0.776254,0.780802,0.560000,0.228228,0.533333,0.440521

In [24]:
avg_qwen_ex = df_qwen_ex.select_dtypes(include='number').mean()
avg_qwen_ex

BERT_Precision    0.776884
BERT_Recall       0.767867
BERT_F1           0.772292
ROUGE-1           0.531382
ROUGE-2           0.289666
ROUGE-L           0.473444
ROUGE_Score       0.431497
dtype: float64

In [25]:
data = {
    'avg_gemma_ab': avg_gemma_ab,
    'avg_llama_ab': avg_llama_ab,
    'avg_qwen_ab': avg_qwen_ab
}

comparison_df = pd.DataFrame(data, index=['BERT_Precision', 'BERT_Recall', 'BERT_F1', 'ROUGE-1', 'ROUGE-2', 'ROUGE-L', 'ROUGE_Score'])
comparison_df

                avg_gemma_ab  avg_llama_ab  avg_qwen_ab
BERT_Precision      0.818673      0.797874     0.755832
BERT_Recall         0.816428      0.796602     0.754997
BERT_F1             0.817487      0.797157     0.755359
ROUGE-1             0.635784      0.622739     0.487592
ROUGE-2             0.400735      0.415446     0.220487
ROUGE-L             0.580107      0.573546     0.415945
ROUGE_Score         0.538875      0.537244     0.374675

In [26]:
data = {
    'avg_gemma_ab': avg_gemma_ex,
    'avg_llama_ab': avg_llama_ex,
    'avg_qwen_ab': avg_qwen_ex
}

comparison_df = pd.DataFrame(data, index=['BERT_Precision', 'BERT_Recall', 'BERT_F1', 'ROUGE-1', 'ROUGE-2', 'ROUGE-L', 'ROUGE_Score'])
comparison_df

                avg_gemma_ab  avg_llama_ab  avg_qwen_ab
BERT_Precision      0.841365      0.819609     0.776884
BERT_Recall         0.839486      0.813765     0.767867
BERT_F1             0.840367      0.816330     0.772292
ROUGE-1             0.693513      0.637908     0.531382
ROUGE-2             0.513326      0.454370     0.289666
ROUGE-L             0.676770      0.612012     0.473444
ROUGE_Score         0.627870      0.568097     0.431497